### ISSUE TITLE
In Game Torpedo Calculator on Holo Map 

### ISSUE THREAD

**Issue by Xuptio** [cc2modteam/revolution-mod#26]
I've updated code in the holomap script to automatically calculate the bearing and activation delay for torpedos. 
I think this makes torpedo play more fun and engaging by making them easier to use. 
Was relatively easy to implement too. 

Watch the calculator in action: 
https://www.youtube.com/watch?v=a-6FSV7e2LQ

![image](https://github.com/user-attachments/assets/fbf0f51b-e011-40b5-996a-92969921ee34)

**Comment by inorton** [comment]
That looks good, but does it need to repeat the bearing since it's on the line below anyway?

**Comment by Xuptio** [comment]
No we can remove it. 
Updated both to below... 
Had to move the ACC <name> a small bit to the right 

![image](https://github.com/user-attachments/assets/7c561ea0-acb8-49f7-9a5f-a56c652ee7eb)
