### ISSUE TITLE
Feature: Vehicle HUD Map Variable Zoom

### ISSUE THREAD

**Issue by Pointclearius** [cc2modteam/revolution-mod#8]
Zoom in/out on the Vehicle HUD Map based upon altitude. Between 100-1000 keep as normal. Above 1000 zoom out to give a decent view of the surround area, 5km? 

Other suggestions:
Above 1900 zoom out considerably, maybe able to see adjacent islands? Not sure if it'll work due to scaling.
Below 100, zoom in to have a better idea of the surrounding area when in control of a ground vehicle.

**Comment by inorton** [comment]
Done and released 2024-01-26
